events { worker_connections 1024; }
http {
    server_tokens off;
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate /etc/ssl/certs/infisical.crt;
        ssl_certificate_key /etc/ssl/private/infisical.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        location / {
            proxy_pass http://infisical:8080;
            proxy_set_header Host $host;
        }
    }
}
